### ISSUE TITLE
Add flags to language selector

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#1]
Current language menu is not intuitive, because it's "text only", please add country flags to menu! @knicos

**Comment by knicos** [comment]
This was removed deliberately because countries and languages are not the same thing. Generally, the advice is not to use flags.

**Comment by LaruX75** [comment]
Really? So reason is accessibility? Ok.

**Comment by knicos** [comment]
Combined with political correctness. Why should a US citizen have to choose a British flag and why is Finnish using the Finnish flag when Finland has 3 official languages.
