### ISSUE TITLE
"Only images can be dropped here" error

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#13]
I understand that implementation of web sites is case spesific and technological choises are different. 
However, "only images can be dropped here" error appears also while draging' dropping photo e.g from site like this: https://web.papunet.net/sites/default/files/kuvapankki/20130313/kissi.jpg

URL is pointing to image itself. When that image is opened in browser tab and tried to drag into TM, issue "only images..." will appear. 

Is this bug or feature?

**Comment by knicos** [comment]
This works for me in Chrome on Linux and is likely browser / system specific. There may not be anything that I can do.

**Comment by LaruX75** [comment]
I use also chrome. Hmm. I will check e.g. to restart browser..

**Comment by LaruX75** [comment]
Well, my students used tm machine today withous issues. I really need to reboot my mac :).. I will close this issue.
