### ISSUE TITLE
Deploy view: classifier get's stuck (and gives weird error) if rear camera is not allowed 

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#16]
Deploy view: classifier get's stuck (and gives weird error) if rear camera is not allowed. It should accept missing camera, because images can be also opened from the folder!

**Comment by knicos** [comment]
Related to this. If they deny camera access then peer-2-peer will not work. This is a browser security restriction.

**Comment by knicos** [comment]
I'll add a better error message, but the webcam MUST be accepted or peer-2-peer cannot function at all.

**Comment by LaruX75** [comment]
Ok. They understand that camera needs to be accepted, however, without warning they doesn't know that camera needs to be allowed :)

So, error message would be very good addition.

**Comment by LaruX75** [comment]
Yep, this issue is related to android phone(s) and chrome browser(s). Two separate students got that error yesterday while using deploy view.

**Comment by knicos** [comment]
An update tonight will prevent the use of "Deploy" without webcam or gives an error saying that the camera must be allowed (but only after they deny it because I don't want any more messages all over a clean interface).

**Comment by LaruX75** [comment]
Very good! Thanks!
