### ISSUE TITLE
Deploy view: classifier get's stuck and gives error when user moves from rear cam to front cam

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#17]
Deploy view: classifier get's stuck and gives error when user moves from rear cam to front cam. Can be same bug than in previous issue.

**Comment by knicos** [comment]
Can you specify the device? This works on my Android + Chrome phone. There is an issue if multiple browser tabs are trying to use a camera at the same time, perhaps this is related? I will see if I can detect something but often the browser doesn't provide information about these problems.

**Comment by knicos** [comment]
Also works fine on my iPhone + Safari.

**Comment by LaruX75** [comment]
It seems to happen when user is using android device

**Comment by knicos** [comment]
Possibly. Did they have two TM tabs open at the same time on their phone? I know that is a problem ... I might be able to do something to fix it but it is a lot of work.

**Comment by LaruX75** [comment]
I don't know about tabs. Issue seems to be pretty rare. Today we used same feature with another class of students without problems. 

If you know that solution is laborous, don't use your time for that. Seems to be rare problem.
