### ISSUE TITLE
DESKTOP: Input view & classifier: the classifier crashes if the camera is not allowed

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#18]
If user doesn't allow webcam to be used, classifier doesn't work. However, it doesn't warn user about this phenomena. This is very confusing for end-users who quite often doesn't allow cam access for webapps. 

I suggest that user interface would warn user that he/she should allow webcam access to get classifier running OR maybe better aproach would be to allow classifier to run without webcam access if photo folder or external device is used anyway instead of webcam.

Now disabled webcam access seems to be blocking classifier to run.

**Comment by knicos** [comment]
This isn't true. You can still add a file. The classifier just needs some input to do anything at all otherwise what is it classifying?

**Comment by knicos** [comment]
However, there will be an update tonight that automatically switches to the "File" input if the webcam is not available.

**Comment by LaruX75** [comment]
Aaa.. ok. That automatic switch would clarify the issue! Now issue is UX issue: user doesn't know that it works, because camera is default and it's not allowed by the user. 

But good that solution is around the corner :)
