### ISSUE TITLE
Classifier: share dialog: missing titles

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#19]
Share dialog got new function when CLONE code was added to it. In current form it has two functionalitis in menu:
- clone the teachable machine
- use model in external tool

However, share menu doesn't offer intuitive interface which would explain these two different use cases. 

I suggest that share menu should have titles as it follows:

TITLE: Share a clone of machine
text text text

TITLE: Use classifier model in external tool 
text text text

![image](https://github.com/knicos/genai-tm/assets/148368959/61bdfa82-6309-4c4b-b0e5-8f6d844c3376)

**Comment by knicos** [comment]
This is precisely why I didn't want the extra features ... we now have to start adding increasingly massive amount of explanatory text into the tool.

Alternative to expanding that dialog even more: remove the "Share" button and instead add a menu similar to the class menu which has two options 1) Share a clone of the project, 2) Use with other applications. Downside, it is slightly more hidden behind a menu but it is consistent with the classes.

**Comment by LaruX75** [comment]
I prefer that menu! Share feature is anyway secondary feature for user. So it's logical that it can be opened from "three dots menu"

Good idea!
