### ISSUE TITLE
"copy link" feature has wrong link (classes view, bigger qr code with copy code)

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#21]
I did test that "make qr code bigger to get also link" feature. However, link what I got was just "https://tm.generation-ai-stn.fi/image/general" .. 

So I actually I got just link to main view of the classifier. So, to put in short: link feature doesnt work :)

**Comment by knicos** [comment]
Yep. I noticed this too late :(

**Comment by LaruX75** [comment]
bug appear both in "classes" and "input" views
