### ISSUE TITLE
Support for uploading/dragging folders? (student could move/upload folder with images to class)

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#25]
Support for uploading/dragging folders? (student could move/upload folder with images to class)

**Comment by knicos** [comment]
No, but they can already select multiple / all images and drag (or upload) all of them in one action.

**Comment by LaruX75** [comment]
> No (well yes maybe but I won't). They can already select multiple / all images and drag (or upload) all of them in one action.

Yep. that student who did ask about it also said same. I promised to ask about a possibility :) Current possibilities are enough of course :)

 I will close this one.
