### ISSUE TITLE
"network issue: no network available"

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#34]
in certain network environments webrtc technology does not work. I discovered this myself when demoing a teaching machine on a computer at the Faculty of Computer Science and Electrical Engineering. They have strict restrictions on their machines. 
Now a similar phenomenon has also occurred on some school networks. I myself have concluded that the problem is in the protocols(?) or similar used by webrtc, because the same message is coming up on both the soma machine and the teaching machine in a particular network environment. 

The annoying thing is that the phenomenon also occurs sporadically on school networks. Is there something that can be done about this?

Here is a letter from a teacher on the subject:
"Hi! Yesterday I tried to try the somekonet with high school students, but the site gave an error message like "network connection not available". I couldn't capture the exact error message as I had to move on with the lesson. I had just tried it on the train a few moments earlier, and the sometext machine worked fine at home. My work partner told me that he had received a similar error message earlier online at work. However, I have also tested it online at work and it worked then, so the error does not always occur. Have you had similar experiences and can you tell me how to solve the problem?"

**Comment by knicos** [comment]
Do you know which version of somekone? Original version?

**Comment by LaruX75** [comment]
Original yep. They don't know about new one.. 🙂 I used TM, not somekone. Same error message (that's why I think that its webrtc vs. network restriction/firewall issue)


***@***.***?anonymous&ep=signature>Varaa aika tavataksesi ***@***.***?anonymous&ep=signature>
________________________________

Jari Laru, KT, yliopistonlehtori
Teknologiatuettu oppiminen ja opetus
Oppimisen ja koulutusteknologian tutkimusyksikkö - LET
Kasvatustieteiden tiedekunta, Oulun yliopisto
________________________________
Jari Laru, Dr. in Education, University Lecturer
Technology Enhanced Learning
Learning & Educational Technology Research Unit (LET)
Faculty of Education, University of Oulu
________________________________

**Comment by knicos** [comment]
Looking at the code, this probably is not actually a real problem with WebRTC but rather a random bug that I can fix. It just fails to retry the connection in some rare cases.

**Comment by LaruX75** [comment]
One reason can be network itself. Restrictions in the network, what do you think? I used in this week laptop which belongs to staff of ITEE faculty (electrical engineers). I wasn't able to use functions which needed p2p network access.. Does it use some special ports or protocols?

Regs. J


***@***.***?anonymous&ep=signature>Varaa aika tavataksesi ***@***.***?anonymous&ep=signature>
________________________________

Jari Laru, KT, yliopistonlehtori
Teknologiatuettu oppiminen ja opetus
Oppimisen ja koulutusteknologian tutkimusyksikkö - LET
Kasvatustieteiden tiedekunta, Oulun yliopisto
________________________________
Jari Laru, Dr. in Education, University Lecturer
Technology Enhanced Learning
Learning & Educational Technology Research Unit (LET)
Faculty of Education, University of Oulu
________________________________

**Comment by LaruX75** [comment]
That port is good to know. Thanks! But it can be also bug!

Nick Pope ***@***.***> kirjoitti 1.11.2024 kello 16.21:



If you can never get it working even when retrying then it could be a network issue but if it sometimes works and sometimes does not then it is more likely a bug in my code that occurs more often on some networks. It needs outgoing TCP port 3478 to be allowed which might be blocked on super strict systems.

**Comment by knicos** [comment]
I've made a possible fix, please let me know if it happens again.

**Comment by LaruX75** [comment]
ok.
