### ISSUE TITLE
Camera doesnt work on acitivity tab

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#35]
Issue: i cant shoot photos in acitivity section, because of inactive (Gray) camera icon!

I have had this issue on different devices/browsers in quite long Time span.

[
![Screenshot_2024-11-03-07-51-06-36_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/973de6b8-bd4b-4b04-8c90-33e65abec1c4)
](url)

**Comment by knicos** [comment]
This feature has never existed. I believe we discussed it during the original interventions and concluded that we should not have it for privacy reasons. Unlike the training data, the action images are sent over a network to other users so these images are a little more sensitive and we would not want to encourage them using pictures from the classroom here.

**Comment by LaruX75** [comment]
Ok. Then visual hint should Be disabled. Now ui is showing blinkinq Square which represents "something is being loaded".  

I recommend that  blinking Squaren Will Be removed and replaced with just background color.

Current version of ui is misleading

**Comment by LaruX75** [comment]
Ok. I thought that it's indication that "camera is loading" :) .. But, if app is working as excpected, maybe I accept it.


***@***.***?anonymous&ep=signature>Varaa aika tavataksesi ***@***.***?anonymous&ep=signature>
________________________________

Jari Laru, KT, yliopistonlehtori
Teknologiatuettu oppiminen ja opetus
Oppimisen ja koulutusteknologian tutkimusyksikkö - LET
Kasvatustieteiden tiedekunta, Oulun yliopisto
________________________________
Jari Laru, Dr. in Education, University Lecturer
Technology Enhanced Learning
Learning & Educational Technology Research Unit (LET)
Faculty of Education, University of Oulu
________________________________
