### ISSUE TITLE
Language setting can't be preset (it's not part of the generated link)

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#37]
I found that all other settings can be pre-set and will be part of the link, but language isn't. This is irritating bug, because machine should be possible to run with pre-set language.

**Comment by knicos** [comment]
It can be done by adding `?lng=fi-FI` to the URL. I could add this automatically but very often we do not wish to force a language on someone

**Comment by LaruX75** [comment]
aaa. Ok. great to know! Thnaks.

**Comment by LaruX75** [comment]
I tested that prefix. It doesnt work if I have chosen custom settings. 
Example: https://tm.gen-ai.fi/image/general?c=N4IghgNhD2DuASBTMAXAtmADiAXCgTgK6IC+QA?lng=fi-FI

My suggestions are:
1. Modify code so that it acceppts url like above. It should also accept url to run TM from the zip-file.. (so, settings + language + zipped tm)
OR
2. Add language setting from settings menu to url which is generated when user will change settings. Current implementation doesn't add language setting as a part of that generated URL. 

WHY this is important: when TM is a part of teaching materials and it's run from that location, user excepts that language will continue from the material to the tool.

**Comment by LaruX75** [comment]
I moved this comment to separa issue.
