### ISSUE TITLE
Language prefix (e.g. ?lng=fi-FI) doesn't work with custom settings

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#39]
I tested that prefix. It doesnt work with custom settings!
Example: https://tm.gen-ai.fi/image/general?c=N4IghgNhD2DuASBTMAXAtmADiAXCgTgK6IC+QA?lng=fi-FI

My suggestions are:

Modify code so that it acceppts url like above. It should also accept url to run TM from the zip-file.. (so, settings + language + zipped tm)
OR
Add language setting from settings menu to url which is generated when user will change settings. Current implementation doesn't add language setting as a part of that generated URL.

WHY this is important: when TM is a part of teaching materials and it's run from that location, user excepts that language will continue from the material to the tool.

**Comment by knicos** [comment]
You use `&lng=fi-FI` if you add it after something else, the "?" changes to an "&".

**Comment by LaruX75** [comment]
Ok. I will test again :)=


Calendar: Book time with Jari Laru ***@***.***?anonymous&ep=pcard>
--

Dr. Jari Laru, University Lecturer, Technology Enhanced Learning
Faculty of Education and Psychology
University of Oulu, Finland
https:/www.linkedin.com/in/jarilaru
+358-40-5118478 (whatsapp)
--
Generation AI project funded by SRC
https://www.generation-ai-stn.fi





Lähettäjä: Nick Pope ***@***.***>
Päivämäärä: tiistaina, 19. marraskuuta 2024 klo 8.37
Vastaanottaja: knicos/genai-tm ***@***.***>
Kopio: Jari Laru ***@***.***>, Author ***@***.***>
Aihe: Re: [knicos/genai-tm] Language prefix (e.g. ?lng=fi-FI) doesn't work with custom settings (Issue #39)


You use &lng=fi-FI if you add it after something else, the "?" changes to an "&".
