### ISSUE TITLE
Actions UX: add BG color dialog or automate it

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#6]
Current version of text tool in actions is not accessible/usable when photo is added as a part of activity.

Text is quite often impossible to read due to lack of contrast.

I suggest two alternatives:

1. Add dialog for setting background color for text. I suggest two options: black and white.

From contrast point of view it would be enough to fix the issue.

2. Automate that: i don't know how to automate BG color setting, but I still want highlight the possibility 😎

**Comment by knicos** [comment]
Issues 101 and 230.

**Comment by LaruX75** [comment]
What does mean "issues 101 and 230" ?

**Comment by knicos** [comment]
I don't use github for development, these are the issue numbers in the real repository. For my reference.

**Comment by LaruX75** [comment]
Aa. That was my thought also!

**Comment by LaruX75** [comment]
@vlebedynska could you contribute to this issue? This is actually one of the last big UI/UX issues on GenAI teachable machine. 

This should be fixed because this is 1/4 of tools in that part of workflow.

**Comment by knicos** [comment]
Done. It automatically selects black or white. Try it here before I update: https://proud-hill-00f04db03-staging.westeurope.2.azurestaticapps.net/image/general

**Comment by LaruX75** [comment]
> Done. It automatically selects black or white. Try it here before I update: https://proud-hill-00f04db03-staging.westeurope.2.azurestaticapps.net/image/general

Works well! Thank you so much!
