### ISSUE TITLE
Open dialog is not logical: "copy shared" ?

### ISSUE THREAD

**Issue by LaruX75** [knicos/genai-tm#9]
<img width="264" alt="epälooginen!" src="https://github.com/knicos/genai-tm/assets/148368959/588c258a-4801-475b-98c7-180c99ef58cf">

See attached image. Button with text "copy shared" doesn't make sense. When I click it will open clone of machine shared by other user. Right?

So, then, I am not actually person who will copy anything.. What is reason for "copy" function next to copy button? Why I should be able to copy code in that context?

I SUGGEST following change: remove a possibility to "copy" code and reprhase "copy code" text like this: "open clone shared via code" .. or just: "open clone" or just: "use clone code" or just: "use code" :-)

**Comment by knicos** [comment]
I was worried that "clone" might not be as easy to understand as copy. It was going to be "Copy shared model" but the button text shouldn't get too long. I'll change it somehow.

**Comment by LaruX75** [comment]
Thanks. Now it's not understable for average user.
